// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthJwtLoginData,
  AuthJwtLoginErrors,
  AuthJwtLoginResponses,
  AuthJwtLogoutData,
  AuthJwtLogoutErrors,
  AuthJwtLogoutResponses,
  CreateItemData,
  CreateItemErrors,
  CreateItemResponses,
  DeleteItemData,
  DeleteItemErrors,
  DeleteItemResponses,
  GetDocumentationUpdateData,
  GetDocumentationUpdateErrors,
  GetDocumentationUpdateResponses,
  ListDocumentationUpdatesData,
  ListDocumentationUpdatesResponses,
  ProposeDocumentationSuggestionsData,
  ProposeDocumentationSuggestionsErrors,
  ProposeDocumentationSuggestionsResponses,
  ReadItemData,
  ReadItemErrors,
  ReadItemResponses,
  RegisterRegisterData,
  RegisterRegisterErrors,
  RegisterRegisterResponses,
  ResetForgotPasswordData,
  ResetForgotPasswordErrors,
  ResetForgotPasswordResponses,
  ResetResetPasswordData,
  ResetResetPasswordErrors,
  ResetResetPasswordResponses,
  SaveDocumentationUpdateData,
  SaveDocumentationUpdateErrors,
  SaveDocumentationUpdateResponses,
  UsersCurrentUserData,
  UsersCurrentUserErrors,
  UsersCurrentUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserResponses,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserErrors,
  UsersPatchCurrentUserResponses,
  UsersPatchUserData,
  UsersPatchUserErrors,
  UsersPatchUserResponses,
  UsersUserData,
  UsersUserErrors,
  UsersUserResponses,
  VerifyRequestTokenData,
  VerifyRequestTokenErrors,
  VerifyRequestTokenResponses,
  VerifyVerifyData,
  VerifyVerifyErrors,
  VerifyVerifyResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthJwtLoginData, ThrowOnError>,
): RequestResult<AuthJwtLoginResponses, AuthJwtLoginErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AuthJwtLoginResponses,
    AuthJwtLoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/auth/jwt/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthJwtLogoutData, ThrowOnError>,
): RequestResult<AuthJwtLogoutResponses, AuthJwtLogoutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    AuthJwtLogoutResponses,
    AuthJwtLogoutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/jwt/logout",
    ...options,
  });

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: Options<RegisterRegisterData, ThrowOnError>,
): RequestResult<
  RegisterRegisterResponses,
  RegisterRegisterErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterRegisterResponses,
    RegisterRegisterErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetForgotPasswordData, ThrowOnError>,
): RequestResult<
  ResetForgotPasswordResponses,
  ResetForgotPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetForgotPasswordResponses,
    ResetForgotPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<ResetResetPasswordData, ThrowOnError>,
): RequestResult<
  ResetResetPasswordResponses,
  ResetResetPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetResetPasswordResponses,
    ResetResetPasswordErrors,
    ThrowOnError
  >({
    url: "/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: Options<VerifyRequestTokenData, ThrowOnError>,
): RequestResult<
  VerifyRequestTokenResponses,
  VerifyRequestTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    VerifyRequestTokenResponses,
    VerifyRequestTokenErrors,
    ThrowOnError
  >({
    url: "/auth/request-verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: Options<VerifyVerifyData, ThrowOnError>,
): RequestResult<VerifyVerifyResponses, VerifyVerifyErrors, ThrowOnError> =>
  (options.client ?? client).post<
    VerifyVerifyResponses,
    VerifyVerifyErrors,
    ThrowOnError
  >({
    url: "/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<UsersCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersCurrentUserResponses,
  UsersCurrentUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    UsersCurrentUserResponses,
    UsersCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
  });

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchCurrentUserData, ThrowOnError>,
): RequestResult<
  UsersPatchCurrentUserResponses,
  UsersPatchCurrentUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UsersPatchCurrentUserResponses,
    UsersPatchCurrentUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
): RequestResult<
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUserData, ThrowOnError>,
): RequestResult<UsersUserResponses, UsersUserErrors, ThrowOnError> =>
  (options.client ?? client).get<
    UsersUserResponses,
    UsersUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
  });

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersPatchUserData, ThrowOnError>,
): RequestResult<UsersPatchUserResponses, UsersPatchUserErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    UsersPatchUserResponses,
    UsersPatchUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/users/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: Options<ReadItemData, ThrowOnError>,
): RequestResult<ReadItemResponses, ReadItemErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    ReadItemResponses,
    ReadItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/items/",
    ...options,
  });

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: Options<CreateItemData, ThrowOnError>,
): RequestResult<CreateItemResponses, CreateItemErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateItemResponses,
    CreateItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: Options<DeleteItemData, ThrowOnError>,
): RequestResult<DeleteItemResponses, DeleteItemErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteItemResponses,
    DeleteItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/items/{item_id}",
    ...options,
  });

/**
 * Propose Documentation Suggestions
 *
 * Generate grounded Edit Suggestions for a documentation update request.
 */
export const proposeDocumentationSuggestions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProposeDocumentationSuggestionsData, ThrowOnError>,
): RequestResult<
  ProposeDocumentationSuggestionsResponses,
  ProposeDocumentationSuggestionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ProposeDocumentationSuggestionsResponses,
    ProposeDocumentationSuggestionsErrors,
    ThrowOnError
  >({
    url: "/documentation-reviews/suggestions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Documentation Updates
 *
 * List previously saved documentation updates.
 */
export const listDocumentationUpdates = <ThrowOnError extends boolean = false>(
  options?: Options<ListDocumentationUpdatesData, ThrowOnError>,
): RequestResult<ListDocumentationUpdatesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListDocumentationUpdatesResponses,
    unknown,
    ThrowOnError
  >({ url: "/documentation-reviews/saved-updates", ...options });

/**
 * Save Documentation Update
 *
 * Persist the user's reviewed documentation update.
 */
export const saveDocumentationUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SaveDocumentationUpdateData, ThrowOnError>,
): RequestResult<
  SaveDocumentationUpdateResponses,
  SaveDocumentationUpdateErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SaveDocumentationUpdateResponses,
    SaveDocumentationUpdateErrors,
    ThrowOnError
  >({
    url: "/documentation-reviews/saved-updates",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Documentation Update
 *
 * Return one saved documentation update with full reviewed suggestions.
 */
export const getDocumentationUpdate = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentationUpdateData, ThrowOnError>,
): RequestResult<
  GetDocumentationUpdateResponses,
  GetDocumentationUpdateErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetDocumentationUpdateResponses,
    GetDocumentationUpdateErrors,
    ThrowOnError
  >({
    url: "/documentation-reviews/saved-updates/{saved_update_id}",
    ...options,
  });
